feat: build script check for go and node versions
kurtosis-tech/kurtosis pull request #240
Opened 2023-03-16 22:33 UTC by eliziario

## Description:
Makes scripts/build.sh checked for specific go and node versions instead of letting build fail later with obscure error during for example, yarn install.  

## Is this change user facing?

* [ ] Yes
* [X] No

## References (if applicable):
[ISSUE: 239](https://github.com/kurtosis-tech/kurtosis/issues/239)

2023-03-16 22:41 UTC, eliziario commented
@kurtosis-tech/engineers It looks like circle ci is refusing to run the pipeline on my PR :-)

2023-03-17 12:21 UTC, mieubrisse commented
Hey @eliziario , thanks for submitting this and congratulations on being our first external contributor!!! @victorcolombo is going to review shortly.

Also, if I'm correctly interpreting your name and you're Brazilian - bem-vindo ao Kurtosis! @victorcolombo é brasileiro, e @galenmarchetti e eu somos americanos apaixonados pelo Brasil e morando aqui :)

2023-03-17 14:41 UTC, eliziario commented
Thanks @mieubrisse! Yes, I am a brazilian and carioca. Tudo beleza ai @victorcolombo and @galenmarchetti? :-)

2023-03-20 11:47 UTC, victorcolombo requested changes
Hey @eliziario ! Thanks for the first contribution on this repo 😃 

Great job on the instructions to install the correct node version, this will help a lot of folks trying to build Kurtosis from scratch.

I left one comment, once that is addressed we are good to merge!

2023-03-20 11:47 UTC, victorcolombo commented on scripts/versions_check.sh
> +check_go_version() {
For Node, I think it's ok to enforce the pinned version for full consistency, given that we are using `NVM` as a version manager, allowing people to have multiple Node versions on their machine.

But in Go's case, we are not (yet) using any version manager, and we would like to allow folks with Go `1.19` and forward to also be able to build Kurtosis, but right now this errors out. Could you add support for this in the function?

2023-03-20 11:48 UTC, victorcolombo commented
Additionally I see there is some CI weirdness going on (we might have a misconfigured permissions), I'm working on it right now to address it

2023-03-20 18:23 UTC, eliziario commented on scripts/versions_check.sh
> +check_go_version() {
I agree, Go is very well-behaved in terms of not introducing break changes, so there is no real benefit in pinning the version, only ensuring the minimal version. I will do this change later today and push it.

2023-03-22 14:35 UTC, victorcolombo approved these changes
Looks good to me @eliziario! I went ahead and approved it, will work on merging this and will let you know once this is released 🚀

2023-03-22 16:21 UTC, merged

2023-03-22 16:42 UTC, victorcolombo commented
@eliziario Sua mudança já tá no release `0.69.2`! 🇧🇷

2023-03-27 23:29 UTC, mieubrisse commented
@eliziario congrats on being the first external contribution to Kurtosis!! I'd love to learn more about what you're thinking of using Kurtosis for; would you be down to schedule a chat with me? You can do so with `kurtosis feedback --calendly` if that sounds good!