fix: enforced kurtosis locator validations when running remote kurtosis package
kurtosis-tech/kurtosis pull request #41
Opened 2023-02-22 07:05 UTC by Peeeekay

Changelog picked up from commits here:

fix: enforced the locator constraint for upload_files too

2023-02-23 04:47 UTC, Peeeekay commented
Refactored the code little bit to support following use-case:

1. kurtosis run github.com/kurtosis-tech/examples/quickstart 
    - while running a remote package, validate if if kurtosis.yml exists in quickstart folder and is following the correct format!
    
2. 
```
def run(plan):
  plan.upload_files(src="github.com/kurtosis-tech/examples/quickstart/default.conf.tmpl", ...)
```
While using the `upload_files` in starlark; validate if the src is correct locator i.e it belongs to a package which contains valid kurtosis.yml.

2023-02-23 10:21 UTC, h4ck3rk3y commented
@Peeeekay can you make the title nicer, you already have a conventional commit for the upload bit, maybe the title can be just about the remote package.

2023-02-23 10:42 UTC, h4ck3rk3y requested changes
i just have some concerns about git_package_content_provider, with all the new helpers, i just want to make sure we can still navigate this code base.

Functionally looks good.

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +
lets make sure that these links are in the user_support_constants test in the CLI (or create one in core?)

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +	pathToKurtosisYaml := path.Join(packageAbsolutePathOnDisk, startosis_constants.KurtosisYamlName)
nice :)

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +	if interpretationError = validateKurtosisYaml(pathToKurtosisYaml, provider.packagesDir); interpretationError != nil {
can we reuse the `validateKurtosisYamlExistsAndIsValid` here to cover  L66-L73?

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +		return startosis_errors.WrapWithInterpretationError(err, "Error occurred while verifying whether '%v' belongs to a Kurtosis package.", fileInsidePackageUrl)
side(not you) - I wonder whether if we should stop wrapping Go errors inside Starlark, sometimes it gets confusing.

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/commons/yaml_parser/kurtosis_yaml.go
> +		return nil, stacktrace.Propagate(err, "Error occurred while reading the contents of %v", absPathToKurtosisYaml)
good catch

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/commons/yaml_parser/kurtosis_yaml.go
> +		return nil, stacktrace.Propagate(err, "Error occurred while reading the contents of %v", absPathToKurtosisYaml)
lets put the '%v' in quotes

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +	if err := validateKurtosisPackageInternal(kurtosisYaml, absPathToKurtosisYmlInThePackage, packageDir); err != nil {
lets rename these helpers, why does validateKurtosisYaml call validateKurtosisPackageInternal?

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
>  	}
can/should lines 59/60 be moved after the atomic clone?

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func validateKurtosisPackageInternal(kurtosisYaml *yaml_parser.KurtosisYaml, absPathToKurtosisYmlInThePackage string, packageDir string) *startosis_errors.InterpretationError {
can we rename this to validateKurtosisPackageName?

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func validateKurtosisPackageInternal(kurtosisYaml *yaml_parser.KurtosisYaml, absPathToKurtosisYmlInThePackage string, packageDir string) *startosis_errors.InterpretationError {
whats the "External" of this "Internal"?

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func validateKurtosisYaml(absPathToKurtosisYmlInThePackage string, packageDir string) *startosis_errors.InterpretationError {
lets stick some comments on top

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func validateKurtosisYamlExistsAndIsValid(fileInsidePackageUrl string, packagesDir string) *startosis_errors.InterpretationError {
this seems to be doing a lot

1. its validating whether the passed link is inside a package (the name does not tell this at all)
2. then its validating the Kurtosis package

This seems a bit smelly, can it do less and be named better?

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func validateKurtosisYamlExistsAndIsValid(fileInsidePackageUrl string, packagesDir string) *startosis_errors.InterpretationError {
this is only used at one place, I am  happy if that place has two different calls to `checkIfFileIsInAValidPackage` and `validateKurtosisYaml`

2023-02-23 10:42 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +	maybeKurtosisYamlPath, err := checkIfFileIsInAValidPackage(fileInsidePackageUrl, packagesDir)
why does a "check" return a non boolean value? should this be "getKurtosisYamlForFileUrl"?

2023-02-23 15:23 UTC, Peeeekay commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func validateKurtosisYamlExistsAndIsValid(fileInsidePackageUrl string, packagesDir string) *startosis_errors.InterpretationError {
you are right; in the hindsight seems like over abstractions on my part; let me do that.

2023-02-23 17:50 UTC, Peeeekay commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +		return startosis_errors.WrapWithInterpretationError(err, "Error occurred while verifying whether '%v' belongs to a Kurtosis package.", fileInsidePackageUrl)
yeah; it is something we need to discuss as team -- handling errors properly.

2023-02-23 17:52 UTC, Peeeekay commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +
done

2023-02-24 11:06 UTC, h4ck3rk3y approved these changes

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +	if interpretationError = validateKurtosisYml(pathToKurtosisYaml, provider.packagesDir); interpretationError != nil {
lets be consistent between Yaml Yml

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +
the benefit of having this all in core would be that we could just re use the constant within core & make sure that the link here is there, and tested. Perhaps we need a broader "links" module or something. To me this is fine for now.

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +	maybeKurtosisYamlPath, err := getOptionalKurtosisYmlPathForFileUrl(pathToFile, provider.packagesDir)
Yml YAML Yaml inconsistencies, lets go with one, Yaml seems like what you have been usign at most places

Does it have to be `getOptional`? I mean `its os.ReadFile` it can fail, and it isn't `os.OptionalReadFile`

is it a FileUrl or just a file now? `pathToFile` sounds like its a path on disk.

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +		return "", startosis_errors.NewInterpretationError("%v is not found in the path of '%v'; files can only be accessed from Kurtosis packages. For more information, go to: %v", startosis_constants.Kur
curious can we simply throw an error from `getOptionalKurtosisYmlPathForFileUrl` if we can't access it / doesn't exist? is that function useful if it doesn't provide yml

```
getKurtosisYmlPathForFile(filePath, packagesDir) -> ymlPath, err {
/// 
if errorfindingyml {
    return errorfindingyml
}

if path == empty {
   return ymlNotFoundErr
}

return ymlPath, nil
}
```

Thoughts?

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +// this method validates the contents of the kurtosis yaml found at path identified by the absPathToKurtosisYmlInThePackage
kurtosis -> Kurtosis

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +// this method validates the contents of the kurtosis yaml found at path identified by the absPathToKurtosisYmlInThePackage
this also checks if the location matches whats expected

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func validatePackageNameMatchesKurtosisYmlLocation(kurtosisYaml *yaml_parser.KurtosisYaml, absPathToKurtosisYmlInThePackage string, packageDir string) *startosis_errors.InterpretationError {
Yml Yaml YAML

2023-02-24 11:06 UTC, h4ck3rk3y commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +func getOptionalKurtosisYmlPathForFileUrlInternal(absPathToFile string, packagesDir string, stat func(string) (os.FileInfo, error)) (string, *startosis_errors.InterpretationError) {
yml/yaml/YAML

2023-02-26 03:26 UTC, Peeeekay commented on core/server/api_container/server/startosis_engine/startosis_packages/git_package_content_provider/git_package_content_provider.go
> +		return "", startosis_errors.NewInterpretationError("%v is not found in the path of '%v'; files can only be accessed from Kurtosis packages. For more information, go to: %v", startosis_constants.Kur
i leave it for now; only called once.. i did the error outside cause i had access `fileInsidePackageUrl` for nice error message.. i could always pass it down the method `getKurtosisYmlPathForFile` but seemed unnecessary.. also did not wanted to wrap both error messages ( not found and unexpected err) into one as well.

2023-02-27 16:21 UTC, merged